language: node_js
node_js:
- '7'
before_install:
- npm install -g npm@'^5.10.0'
- npm install -g RadonApp/radon-extension-build#$TRAVIS_BRANCH || npm install -g RadonApp/radon-extension-build#develop
install:
- neb travis:install $TRAVIS_BRANCH
- neb package:validate
- git diff --exit-code
script:
- npm run test
- npm run lint
- if [ ! -f ./Build/Coverage/lcov.info ]; then exit 1; fi
after_success:
- npm install -g coveralls
- cat ./Build/Coverage/lcov.info | coveralls
deploy:
  provider: npm
  email: ci@radon.app
  api_key:
    secure: YVrjx5gZE6kAU/p7pFTFLFbkWwMaQIRPJhpE5Jg6IWKsd/1lgyVSbr/4Hxes8feoWlFaiawQJB9dXxO0+6EHNSaAy6jc5FPATLzXWEEzXHmIaozMAjFX0/fBuHwZIPAS/CdEFtzBumU6qmYRjRrP6JazzKJW3uBCRQs+OrSnBG9V6ec5gtroHieMaCwMrUkpsev3vP5wlnwZJtjb0hBv+qhoiT0Gm1n1vsJrK9gGzCcl8U+nTOjl2RYZklEUn0DVb5g5dUUez0D0cuc3sK2mJjKDvgDvGQsETpbF1RhpSosmRgWCOmTFlv3V7+JLY0kb5cOBuSOHZWwW5LhQrkzgT9ChC1sw2klPWqLRZBywNE4wSs30CTb0Z9eNdf8Mfqse/GxCYYhe2rIQI2mUoXf/b2oTY/UbNhcnOjjaoFFp34lwhOlFUIa3izGoJ9/mxmWKt/1xQ6oD5Bsar3Oo3hhLC7WKDDwjCiizlGhVFGtHves0VOCdUqYVkPS/alh1paGy1t09g8l4AEdnvze5qQQOxzEjt6GIEPxyRQC3fYgJsYT2+lcCMOhUjc5cbnN7oRPI338nbttcBQ+LmXPC5vCZ/D/3pefgePHVw0v8vI0JKQi0s1+xvTBnXxE8Elfq5dQKjG49wbLitQQ0qIwyBjHbDRNxSPdwhV+ACYHdsy7PWVM=
  on:
    tags: true
    repo: RadonApp/radon-extension-plugin-lastfm
